### ISSUE TITLE
Selected days shown on multiple months

### ISSUE THREAD

**Issue by yehudahkay** [ChiperSoft/Kalendae#140]
If the calendar shows multiple months the selected day/days are shown on both months. I think visually it would make more sense if the days would only be selected in the active month.

**Comment by ChiperSoft** [comment]
This is intentional. If you wish to override this behavior, you overwrite the styles on the out of month days by targeting the css selector `.k-out-of-month.k-selected` and setting it back to the values in `.k-out-of-month`

**Comment by ChiperSoft** [comment]
Specifically the following will change the out-of-month days back to unselected, if you're using the default styles.

```css
.kalendae .k-days span.k-selected.k-out-of-month {
  color: #ddd;
  border-color: #eee;
  background: #eee;
}
```
